spring:
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinedb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  header: Authorization
  secret: "q3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaPdSgVkYp2s5v8y/B?E(H+MbQeTh"
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh